SiteManager/SiteManager.Web.UI/Controllers/BuildingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SiteManager.Business.Abstract;
using SiteManager.Business.DTOs;
using System.Threading.Tasks;

namespace SiteManager.Web.UI.Controllers
{
    [Authorize]
    public class BuildingController : Controller
    {
        private readonly IBuildingService _buildingService;

        public BuildingController(IBuildingService buildingService)
        {
            _buildingService = buildingService;
        }
        public async Task<IActionResult> Index()
        {
            var buildings = await _buildingService.GetAll();
            return View(buildings.Data);
        }

        [Authorize(Roles ="Admin")]
        [HttpGet]
        public IActionResult AddBuilding()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> AddBuilding(BuildingDto building)
        {
            if (!ModelState.IsValid)
                return View(building);

            await _buildingService.Add(building);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> UpdateBuilding(int id)
        {
            var building = await _buildingService.GetById(id);
            return View(building.Data);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult UpdateBuilding(BuildingDto building)
        {
            if(!ModelState.IsValid)
                return View(building);

            _buildingService.Update(building);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public IActionResult DeleteBuilding(int id)
        {
            _buildingService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

SiteManager/SiteManager.Web.UI/Views/Building/AddBuilding.cshtml
@model BuildingDto

<form asp-controller="Building" asp-action="AddBuilding" method="post">
    <div class="form-group">
        <label asp-for="BuildingName" class="control-label">Blok Adı</label>
        <input type="text" asp-for="BuildingName" class="form-control" />
        <span asp-validation-for="BuildingName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="NumberOfFlats" class="control-label">Toplam Daire Sayısı</label>
        <input type="text" asp-for="NumberOfFlats" class="form-control" />
        <span asp-validation-for="NumberOfFlats" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-success">Ekle</button>
</form>

SiteManager/SiteManager.Web.UI/Views/Building/Index.cshtml
@model ICollection<BuildingDto>

<div>
    <a class="btn btn-success" asp-action="AddBuilding" asp-controller="Building">Yeni Blok Ekle</a>
</div>
<br />
<table class="table table-dark table-hover">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Blok Adı</th>
            <th scope="col">Toplam Daire Sayısı</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var building in Model)
        {
            <tr>
                <th scope="row">@building.Id</th>
                <td>@building.BuildingName</td>
                <td>@building.NumberOfFlats</td>
                <td>
                    <a class="btn btn-warning" asp-controller="Building" asp-action="UpdateBuilding" asp-route-id="@building.Id">
                        Güncelle
                    </a>
                </td>
                <td>
                    <a class="btn btn-danger" asp-controller="Building" asp-action="DeleteBuilding" asp-route-id="@building.Id">
                        Sil
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

SiteManager/SiteManager.Web.UI/Views/Building/UpdateBuilding.cshtml
@model BuildingDto

<form asp-controller="Building" asp-action="UpdateBuilding" method="post">
    <div class="form-group">
        <label asp-for="BuildingName" class="control-label">Blok Adı</label>
        <input type="text" asp-for="BuildingName" class="form-control" />
        <span asp-validation-for="BuildingName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="NumberOfFlats" class="control-label">Toplam Daire Sayısı</label>
        <input type="text" asp-for="NumberOfFlats" class="form-control" />
        <span asp-validation-for="NumberOfFlats" class="text-danger"></span>
    </div>
    <input type="hidden" asp-for="Id"/>
    <button type="submit" class="btn btn-success">Güncelle</button>
</form>