SiteManager/SiteManager.Web.UI/Controllers/AnnouncementController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SiteManager.Business.Abstract;
using SiteManager.Business.DTOs;
using System.Threading.Tasks;

namespace SiteManager.Web.UI.Controllers
{
    [Authorize]
    public class AnnouncementController : Controller
    {
        private readonly IAnnouncementService _announcementService;

        public AnnouncementController(IAnnouncementService announcementService)
        {
            _announcementService = announcementService;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var announcements = await _announcementService.GetAll();
            return View(announcements.Data);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult AddAnnouncement()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> AddAnnouncement(AnnouncementDto announcement)
        {
            if (!ModelState.IsValid)
                return View(announcement);

            await _announcementService.Add(announcement);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> UpdateAnnouncement(int id)
        {
            var announcement = await _announcementService.GetById(id);
            return View(announcement.Data);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult UpdateAnnouncement(AnnouncementDto announcement)
        {
            if (!ModelState.IsValid)
                return View(announcement);

            _announcementService.Update(announcement);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public IActionResult DeleteAnnouncement(int id)
        {
            _announcementService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

SiteManager/SiteManager.Web.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SiteManager.Business.Abstract;
using SiteManager.Business.DTOs;
using SiteManager.Domain.Concrete;
using SiteManager.Web.UI.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace SiteManager.Web.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly IAnnouncementService _announcementService;
        private readonly IBuildingService _buildingService;
        private readonly IExpenseService _expenseService;
        private readonly IExpenseTypeService _expenseTypeService;
        private readonly IFlatService _flatService;
        private readonly IUserService _userService;
        private readonly IMessageService _messageService;
        private readonly SignInManager<User> _signInManager;
        private readonly UserManager<User> _userManager;

        public HomeController(IAnnouncementService announcementService, IBuildingService buildingService, IExpenseService expenseService, IExpenseTypeService expenseTypeService, IFlatService flatService, IUserService userService, IMessageService messageService, SignInManager<User> signInManager, UserManager<User> userManager)
        {
            _announcementService = announcementService;
            _buildingService = buildingService;
            _expenseService = expenseService;
            _expenseTypeService = expenseTypeService;
            _flatService = flatService;
            _userService = userService;
            _messageService = messageService;
            _signInManager = signInManager;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var announcements = await _announcementService.GetAll();
            return View(announcements.Data);
        }
        public async Task<IActionResult> GetAllBuilding()
        {
            var buildings = await _buildingService.GetAll();
            return View(buildings.Data);
        }
        public async Task<IActionResult> GetAllFlat()
        {
            var flats = await _flatService.GetAllFlats();
            return View(flats.Data);
        }
        public async Task<IActionResult> GetExpense()
        {
            var user = _userService.GetUserSession();
            var expense = await _expenseService.GetAllExpenses();
            var expenseDetail = expense.Data.Where(x => x.IsPayment == false && x.UserName == user.UserName).ToList();
            return View(expenseDetail);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SiteManager/SiteManager.Web.UI/Views/Home/GetAllBuilding.cshtml
@model IEnumerable<BuildingDto>

<table class="table table-dark table-hover">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Bina Adı</th>
            <th scope="col">Toplam Daire Sayısı</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var building in Model)
        {
            <tr>
                <th scope="row">@building.Id</th>
                <td>@building.BuildingName</td>
                <td>@building.NumberOfFlats</td>
            </tr>
        }
    </tbody>
</table>

SiteManager/SiteManager.Web.UI/Views/Home/GetAllFlat.cshtml
@model List<FlatDto>

<table class="table table-dark table-hover">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Blok Bilgisi</th>
            <th scope="col">Daire Numarası</th>
            <th scope="col">Daire Sahibi</th>
            <th scope="col">Daire Tipi</th>
            <th scope="col">Daire Durumu</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var flat in Model)
        {
            <tr>
                <td>@flat.BuildingName</td>
                <td>@flat.FlatNumber</td>
                <td>@flat.UserName</td>
                <td>@flat.TypeOfFlat</td>
                <td>
                    @if (flat.IsEmpty)
                    {
                        <span>Dolu</span>
                    }
                    else
                    {
                       <span>Boş</span> 
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

SiteManager/SiteManager.Web.UI/Views/Home/GetExpense.cshtml
@model List<ExpenseDto>

<table class="table table-dark table-hover">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Daire Sahibi</th>
            <th scope="col">Daire Numarası</th>
            <th scope="col">Fatura Tipi</th>
            <th scope="col">Fatura Fiyatı</th>
            <th scope="col">Son Ödeme Tarihi</th>
            <th scope="col">Ödeme Bilgisi</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var expense in Model)
        {
            <tr>
                <th scope="row">@expense.Id</th>
                <th>@expense.UserName</th>
                <th>@expense.FlatNumber</th>
                <th>@expense.TypeName</th>
                <th>@expense.Price</th>
                <th>@expense.InvoiceDate.ToString("dd.MM.yyyy")</th>
                <th>
                    @if (expense.IsPayment)
                    {
                        <span>Ödendi</span>
                    }
                    else
                    {
                       <span>Ödenmedi</span> 
                    }
                </th>
                <th>
                    <a href="payment" class="btn btn-success">Öde</a>
                </th>
            </tr>
        }
    </tbody>
</table>

SiteManager/SiteManager.Web.UI/Views/Home/Index.cshtml
@model ICollection<AnnouncementDto>

<div>
    <a class="btn btn-success" asp-action="AddAnnouncement" asp-controller="Announcement">Yeni Duyuru Ekle</a>
</div>
<br />
<table class="table table-dark table-hover">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Duyuru</th>
            <th scope="col">İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var announcement in Model)
        {
            <tr>
                <th scope="row">@announcement.Id</th>
                <td>@announcement.Content</td>
                <td>
                    <a class="btn btn-warning" asp-controller="Announcement" asp-action="UpdateAnnouncement" asp-route-id="@announcement.Id">
                        Güncelle
                    </a>
                </td>
                <td>
                    <a class="btn btn-danger" asp-controller="Announcement" asp-action="DeleteAnnouncement" asp-route-id="@announcement.Id">
                        Sil
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>