SiteManager/SiteManager.Web.UI/Controllers/AuthController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SiteManager.Business.DTOs;
using SiteManager.Domain.Concrete;
using System.Threading.Tasks;

namespace SiteManager.Web.UI.Controllers
{
    public class AuthController : Controller
    {
        private readonly SignInManager<User> _signInManager;
        private readonly UserManager<User> _userManager;

        public AuthController(SignInManager<User> signInManager, UserManager<User> userManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
        }
        public IActionResult Login(string returnUrl)
        {
            return View(new LoginDto
            {
                ReturnURL = returnUrl
            });
        }
        
        [HttpPost]
        public async Task<IActionResult> Login(LoginDto model)
        {
            if(!ModelState.IsValid)
                return View(model);

            var user = await _userManager.FindByEmailAsync(model.Email);
            if (user == null)
                return View(model);

            var result = await _signInManager.PasswordSignInAsync(user, model.Password, true, false);
            if (result.Succeeded)
                return Redirect(model.ReturnURL ?? "/Home/Index");

            return View(model);
        }
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

SiteManager/SiteManager.Web.UI/Controllers/ExpenseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SiteManager.Business.Abstract;
using SiteManager.Business.DTOs;
using System;
using System.Threading.Tasks;

namespace SiteManager.Web.UI.Controllers
{
    [Authorize]
    public class ExpenseController : Controller
    {
        private readonly IExpenseService _expenseService;
        private readonly IExpenseTypeService _expenseTypeService;
        private readonly IFlatService _flatService;

        public ExpenseController(IExpenseService expenseService, IExpenseTypeService expenseTypeService, IFlatService flatService)
        {
            _expenseService = expenseService;
            _expenseTypeService = expenseTypeService;
            _flatService = flatService;
        }

        public async Task<IActionResult> Index()
        {
            var expense = await _expenseService.GetAllExpenses();
            return View(expense.Data);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> AddExpense()
        {
            var expenseType = await _expenseTypeService.GetAll();
            var flat = await _flatService.GetAll();
            var createExpense = new CreateExpenseDto
            {
                ExpenseTypes = expenseType.Data,
                Flats = flat.Data,
            };
            
            return View(createExpense);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> AddExpense(CreateExpenseDto createExpense)
        {
            if(!ModelState.IsValid)
                return View(createExpense);

            createExpense.InvoiceDate = DateTime.Now;
            createExpense.IsPaid = false;

            await _expenseService.Add(createExpense);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> UpdateExpense(int id)
        {
            var flat = await _flatService.GetAll();
            var expenseType = await _expenseTypeService.GetAll();
            var expense = await _expenseService.GetById(id);

            var updateExpense = new UpdateExpenseDto()
            {
                Id = expense.Data.Id,
                Flats = flat.Data,
                ExpenseTypes = expenseType.Data,
                Price = expense.Data.Price,
                InvoiceDate = DateTime.Now,
                IsPayment = expense.Data.IsPayment
            };

            return View(updateExpense);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult UpdateExpense(UpdateExpenseDto updateExpense)
        {
            if (!ModelState.IsValid)
                return View(updateExpense);

            _expenseService.Update(updateExpense);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public IActionResult DeleteExpense(int id)
        {
            _expenseService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

SiteManager/SiteManager.Web.UI/Controllers/FlatController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SiteManager.Business.Abstract;
using SiteManager.Business.DTOs;
using System.Threading.Tasks;

namespace SiteManager.Web.UI.Controllers
{
    [Authorize]
    public class FlatController : Controller
    {
        private readonly IUserService _userService;
        private readonly IBuildingService _buildingService;
        private readonly IFlatService _flatService;

        public FlatController(IUserService userService, IBuildingService buildingService, IFlatService flatService)
        {
            _userService = userService;
            _buildingService = buildingService;
            _flatService = flatService;
        }

        public async Task<IActionResult> Index()
        {
            var flats = await _flatService.GetAllFlats();
            return View(flats.Data);
        }

        [Authorize(Roles ="Admin")]
        [HttpGet]
        public async Task<IActionResult> AddFlat()
        {
            var building = await _buildingService.GetAll();
            var user = await _userService.GetAll();
            var flat = new CreateFlatDto
            {
                Buildings = building.Data,
                Users = user.Data
            };

            return View(flat);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> AddFlat(CreateFlatDto createFlat)
        {
            if(!ModelState.IsValid)
                return View(createFlat);

            await _flatService.Add(createFlat);
            return RedirectToAction("Index");
        }

        [Authorize(Roles ="Admin")]
        [HttpGet]
        public async Task<IActionResult> UpdateFlat(int id)
        {
            var user = await _userService.GetAll();
            var building = await _buildingService.GetAll();
            var flat = await _flatService.GetById(id);

            var updateFlat = new UpdateFlatDto()
            {
                Id = flat.Data.Id,
                Users = user.Data,
                Building = building.Data,
                FlatNumber = flat.Data.FlatNumber,
                IsEmpty = flat.Data.IsEmpty,
                TypeOfFlat = flat.Data.TypeOfFlat
            };

            return View(updateFlat);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult UpdateFlat(UpdateFlatDto updateFlat)
        {
            if (!ModelState.IsValid)
                return View(updateFlat);

            _flatService.Update(updateFlat);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public IActionResult DeleteFlat(int id)
        {
            _flatService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

SiteManager/SiteManager.Web.UI/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SiteManager.Business.Abstract;
using SiteManager.Business.DTOs;
using System.Threading.Tasks;

namespace SiteManager.Web.UI.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }
        public async Task<IActionResult> Index()
        {
            var userList = await _userService.GetAll();
            return View(userList.Data);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult AddUser()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> AddUser(RegisterDto registerDto)
        {
            if (!ModelState.IsValid)
            {
                return View(registerDto);
            }

            await _userService.CreateUser(registerDto);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> UpdateUser(string id)
        {
            var user = await _userService.GetById(id);
            return View(user.Data);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> UpdateUser(UserDto userDto)
        {
            if (!ModelState.IsValid)
                return View(userDto);

            await _userService.UpdateUser(userDto);
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult UserDelete(string id)
        {
            _userService.DeleteUser(id);
            return RedirectToAction("Index");
        }
    }
}

SiteManager/SiteManager.Web.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Nadir Korkut - Site Yönetim Sistemi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Site Yönetimi</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Announcement" asp-action="Index">Duyurular</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Building" asp-action="Index">Binalar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Flat" asp-action="Index">Daireler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Expense" asp-action="Index">Giderler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ExpenseType" asp-action="Index">Gider Tipleri</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Kullanıcılar</a>
                        </li>
                        <li class="nav-item">
                            <div class="dropdown">
                                <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Mesajlar
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Message" asp-action="InBox">Gelen Kutusu</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Message" asp-action="OutBox">Giden Kutusu</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Message" asp-action="SendMessage">Mesaj Gönder</a>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>

                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <span>Hoşgeldin, @User.Identity.Name</span>
                            <button type="button" class="btn btn-primary">
                                <a class="nav-link" asp-controller="Auth" asp-action="Logout">Çıkış Yap</a>
                            </button>

                        }
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <button type="button" class="btn btn-success">
                                <a class="nav-link" asp-controller="Auth" asp-action="Login">Üye Girişi</a>
                            </button>
                        }
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Site Yönetimi - <a href="https://www.linkedin.com/in/nadirkorkut/">Nadir Korkut</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SiteManager/SiteManager.Web.UI/Views/Shared/_LayoutEmpty.cshtml

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/assets/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="~/assets/css/style.css">
    <link rel="shortcut icon" href="~/assets/images/favicon.ico" />

</head>
<body>
    @RenderBody()
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendors/js/vendor.bundle.base.js"></script>
    <script src="~/assets/js/off-canvas.js"></script>
    <script src="~/assets/js/hoverable-collapse.js"></script>
    <script src="~/assets/js/misc.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>